### ISSUE TITLE
missing usage example & documentation

### ISSUE THREAD

**Issue by AlexanderStohr** [fpelliccioni/cpuid-py#4]
often source codes are very self explanatory.

but sometimes its better to have one example for each API and API calling variation ready to run to better understand and also for instantly testing the functionality of such a module.
especially when the results are often very machine dependent testing on multiple platforms in a comparable fashion is pretty welcomed.

even if reading the source might be quite fine - still having true documentation is as well a quite noticeable worth. and its a way for the developer to express things he knows about that are not that obvious for various reasons, e.g. coming from a lower layer that the average user might not know that well.

is it possible to add a usage example & test script?
is it possible to add documentation?

**Comment by fpelliccioni** [comment]
Hi Alex,

I appreciate and share your thinking.
This is an ad honorem open source project, done in my free time.

> is it possible to add a usage example & test script?
> is it possible to add documentation?

Yes, it is possible, but unfortunately it is not within my plan to do so now, due to lack of time.
PRs are always welcome.

Thank you very much!
